---
# tasks file for debian-ins-apache-selinux
- name: Actualizar paquetes de software
  apt:
    update_cache: yes

- name: Instalar Apache
  apt:
    name:
      - apache2
    state: present

- name: Habilitar Apache al inicio
  systemd:
    name: apache2
    enabled: yes

- name: Iniciar Apache
  systemd:
    name: apache2
    state: started

- name: Permitir tráfico HTTP a través del firewall
  command: 
    cmd: sudo ufw allow http

- name: Permitir tráfico HTTPS a través del firewall
  command: 
    cmd: sudo ufw allow https

- name: Recargar firewall
  command: 
    cmd: sudo ufw reload

- name: Deshabilitar módulo SELinux
  copy:
      src: /home/vagrant/src/recursos/config
      dest: /etc/selinux/config
      owner: root
      group: root
      mode: '0644'

- name: Reiniciar servidor
  reboot:
      reboot_timeout: 60
      post_reboot_delay: 30

- name: Iniciar apache2
  systemd:
    name: apache2
    state: started
...
